# Generated by Django 3.2.8 on 2021-12-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('image_url', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Books Name',
            },
        ),
    ]
